a=input("Enter your name here:-")
print("Hey ",a,"!"," How are you? and whats your age")
b=input("Tell your age:-")
print("Oh! You are",b,"?")
c=input("What is your hobby:-")
print(c,"Oh! that sounds great")
d=input("What is your favourite game?:-")
print(f"Oh {d} thats a greate game")
e=input("wHATS UR FAVOURITE CHATBOT:-")
print("oh if its {} Its a great choice but its not me :( ".format(e))